name = "duoduomaicai"
workers_dev = true
compatibility_date = "2025-04-12"

main = "index.ts"

# 根目录静态资源绑定（你的 HTML/CSS/JS 都在仓库根目录）
[assets]
directory = "./"
binding = "ASSETS"
# 给静态资源设置长缓存
cache_ttl = 31536000  # 单位秒，1年

[observability.logs]
enabled = true
 